### ISSUE TITLE
Add Testing Framework

### ISSUE THREAD

**Issue by jolo-dev** [jolo-dev/aws-s3-python#5]
After googling, a list of possible [Python Testing frameworks](https://dzone.com/articles/top-5-python-frameworks-for-test-automation-in-201).

**Comment by Alig1493** [comment]
I think pytest could be a useful and easy to use addition. Should I add it?

**Comment by jolo-dev** [comment]
@Alig1493 I would love that! Please, go ahead!

**Comment by Alig1493** [comment]
@jolo-dev sure. Please give me some time

**Comment by Alig1493** [comment]
Do you think you could update the pipfile and include the pipfile lock so that I have the same packages and dependencies you're using?

**Comment by jolo-dev** [comment]
@Alig1493 
checkout https://github.com/jolo-dev/aws-s3-python/commit/6d0aa449db5313ec2f7bf40f39ce23baf03e23c7

Just merge with master.

**Comment by jolo-dev** [comment]
Oh, I see that it still uses Python3.5.

If you want, you can use a higher version.

**Comment by Alig1493** [comment]
@jolo-dev I've set up the pytest framework and was hoping to write a test case or two for convenience. However I don't happen to have an AWS account as a result no bucket credentials either. Would it be alright of me to ask you to share your bucket credentials if you had any? Thanks!

**Comment by Alig1493** [comment]
I added one basic test method but I can make it more extensive if I had bucket credentials which I don't. :disappointed: 
You can work on this branch and add your own tests if you want.

**Comment by jolo-dev** [comment]
Hi @Alig1493,

okay, let me see what I can do. 
Thank you so far :)
